version: "2.1"

services:

  db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: mysql:5.7
    ports:
      - ':3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - common_network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 10s
        timeout: 10s
        retries: 10
  api:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app/:/opt/app
    links:
      - db
    ports:
      - '8080:8080'
    networks:
      - common_network
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-dump:

networks:
  common_network: